export const mockPlans = [
  {
    id: 1,
    name: "Plan Poniedziałkowy",
    description: "Koncentracja zajęć w poniedziałki i wtorki",
    isActive: true,
    isFavorite: true,
    totalCredits: 18,
    conflicts: 0,
    lastModified: "2025-06-20",
    classes: [
      {
        id: 1,
        courseName: "Algorytmy i struktury danych",
        courseCode: "Grupa 1",
        instructor: "Elżbieta Kukla",
        time: "08:00 - 09:30",
        day: "Poniedziałek",
        location: "Sala 101",
        credits: 3,
        type: "Wykład",
      },
      {
        id: 2,
        courseName: "Architektura komputerów",
        courseCode: "Grupa 1",
        instructor: "Radosław Michalski",
        time: "10:00 - 11:30",
        day: "Poniedziałek",
        location: "Lab A205",
        credits: 4,
        type: "Laboratorium",
      },
      {
        id: 3,
        courseName: "Fizyka II",
        courseCode: "Grupa 1",
        instructor: "Witold Jacek",
        time: "12:00 - 13:30",
        day: "Poniedziałek",
        location: "Sala Fizyki",
        credits: 3,
        type: "Wykład",
      },
      {
        id: 4,
        courseName: "Analiza matematyczna II",
        courseCode: "Grupa 5",
        instructor: "Aleksander Cieślak",
        time: "14:00 - 15:30",
        day: "Poniedziałek",
        location: "Sala C202",
        credits: 4,
        type: "Wykład",
      },
      {
        id: 5,
        courseName: "Analiza matematyczna II",
        courseCode: "Grupa 5",
        instructor: "Karina Olszak",
        time: "16:00 - 17:30",
        day: "Wtorek",
        location: "Sala D301",
        credits: 4,
        type: "Ćwiczenia",
      },
    ],
  },
  {
    id: 2,
    name: "Plan Rozłożony",
    description: "Równomierne rozłożenie zajęć w ciągu tygodnia",
    isActive: false,
    isFavorite: false,
    totalCredits: 19,
    conflicts: 0,
    lastModified: "2025-06-22",
    classes: [
      {
        id: 6,
        courseName: "Algorytmy i struktury danych",
        courseCode: "Grupa 2",
        instructor: "Elżbieta Kukla",
        time: "09:00 - 10:30",
        day: "Wtorek",
        location: "Sala 103",
        credits: 3,
        type: "Wykład",
      },
      {
        id: 7,
        courseName: "Architektura komputerów",
        courseCode: "Grupa 2",
        instructor: "Elżbieta Kukla",
        time: "11:00 - 12:30",
        day: "Środa",
        location: "Lab B301",
        credits: 4,
        type: "Laboratorium",
      },
      {
        id: 8,
        courseName: "Analiza matematyczna II",
        courseCode: "Grupa 3",
        instructor: "Marian Gewert",
        time: "13:00 - 14:30",
        day: "Środa",
        location: "Sala E201",
        credits: 4,
        type: "Wykład",
      },
      {
        id: 9,
        courseName: "Matematyka dyskretna",
        courseCode: "Grupa 5",
        instructor: "Iuliia Arkhangielska",
        time: "15:00 - 16:30",
        day: "Czwartek",
        location: "Sala F105",
        credits: 3,
        type: "Wykład",
      },
      {
        id: 10,
        courseName: "Systemy operacyjne",
        courseCode: "Grupa 8",
        instructor: "Arkadiusz Warzyjski",
        time: "10:00 - 11:30",
        day: "Piątek",
        location: "Lab G201",
        credits: 5,
        type: "Laboratorium",
      },
    ],
  },
  {
    id: 3,
    name: "Plan Kompaktowy",
    description: "Zajęcia skupione w pierwszej części tygodnia",
    isActive: false,
    isFavorite: false,
    totalCredits: 16,
    conflicts: 1,
    lastModified: "2025-06-18",
    classes: [
      {
        id: 11,
        courseName: "Algorytmy i struktury danych",
        courseCode: "Grupa 4",
        instructor: "Elżbieta Kukla",
        time: "08:00 - 09:30",
        day: "Poniedziałek",
        location: "Sala 102",
        credits: 3,
        type: "Wykład",
      },
      {
        id: 12,
        courseName: "Matematyka dyskretna",
        courseCode: "Grupa 4",
        instructor: "Iuliia Arkhangielska",
        time: "10:00 - 11:30",
        day: "Poniedziałek",
        location: "Sala A205",
        credits: 3,
        type: "Wykład",
      },
      {
        id: 13,
        courseName: "Architektura komputerów",
        courseCode: "Grupa 8",
        instructor: "Arkadiusz Warzyjski",
        time: "12:00 - 14:00",
        day: "Wtorek",
        location: "Lab E301",
        credits: 5,
        type: "Laboratorium",
      },
      {
        id: 14,
        courseName: "Analiza matematyczna II",
        courseCode: "Grupa 3",
        instructor: "Marian Gewert",
        time: "09:00 - 10:30",
        day: "Środa",
        location: "Sala C301",
        credits: 5,
        type: "Ćwiczenia",
      },
    ],
  },
];
