name: E2E Tests
on:
  pull_request:
    branches: [main]
    paths:
      - "3. E2E testing/**"
      - ".github/workflows/e2e-tests.yml"
jobs:
  test:
    timeout-minutes: 60
    defaults:
      run:
        working-directory: "3. E2E testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "3. E2E testing/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --pass-with-no-tests

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
