name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "1. Unit testing/**"
      - ".github/workflows/unit-tests.yml"

jobs:
  unit-tests:
    name: Unit Tests
    defaults:
      run:
        working-directory: "1. Unit testing"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "1. Unit testing/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run coverage
